language: python
python:
  - "3.5"
install:
  - pip3 install coveralls
  - pip install colored
script:
  - python3 -m unittest test_rpn
  - coverage run -m unittest test_rpn
  - coverage report -m
after_success:
  - coveralls
